# Generated by Django 3.2.4 on 2021-07-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('productlowestprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='productvariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('variationtext', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('lastupdated', models.CharField(max_length=50)),
            ],
        ),
    ]
