# Generated by Django 3.2.4 on 2021-07-01 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_productvariation_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='lastupdated',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='productid',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='myapp.products'),
        ),
    ]
