# Generated by Django 3.2.4 on 2021-07-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_productvariation_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='product',
        ),
    ]
